### ISSUE TITLE
Test recirculation control (requires device that has this feature enabled)

### ISSUE THREAD

**Issue by rudybrian** [rudybrian/PyNavienSmartControl#15]
Test with a device that has recirculation to ensure control functions are working properly

**Comment by actionpotato** [comment]
I might be able to test this for you? My unit is supposed to have this feature - but it does not appear in the Navien app?
(Documentation on this is confiusing)

**Comment by rudybrian** [comment]
@actionpotato can you tell me more about your setup? 

Typically you would have either a recirculation schedule or use on-demand recirculation (hot button). In either case you should be able to set the recirculation temperature, but the ability to do so may only be possible with certain model types.

**Comment by rudybrian** [comment]
Tested with both recirculation schedule and hot button.
