### ISSUE TITLE
Test recirculation status printouts (requires device that has this feature enabled)

### ISSUE THREAD

**Issue by rudybrian** [rudybrian/PyNavienSmartControl#18]
Test print functions for systems that have recirculation enabled.

**Comment by actionpotato** [comment]
I will try to test this for you - my navien seems to support this.

**Comment by rudybrian** [comment]
@actionpotato please share the output when using the _-summary_ option with _NavienSmartControl-CLI.py_

For a device with recirculation disabled, this looks something like:
```
--------------
Navien-API V1.0
--------------

---------------------------
Device ID: XXXXXXXXXXXXXXXX
Nickname: YYYYYYYYYY
State: 1
Connected: 3/26/2022 10:04:40 PM
Server IP Address: 13.10.5.75
Server TCP Port Number: 6001
---------------------------

Channel Info
---------------------------
Channel:1
        Device Model Type: NO_DEVICE
        Device Count: 0
        Temp Flag: CELSIUS
        Minimum Setting Water Temperature: 0
        Maximum Setting Water Temperature: 0
        Heating Minimum Setting Water Temperature: 0
        Heating Maximum Setting Water Temperature: 0
        Use On Demand: UNKNOWN
        Heating Control: SUPPLY
        wwsdFlag: OK
        commercialLock: OK
        hotwaterPossibility: OFF
        recirculationPossibility: OFF
        High Temperature: TEMPERATURE_60
        Use Warm Water: OFF
Channel:2
        Device Model Type: NO_DEVICE
        Device Count: 0
        Temp Flag: CELSIUS
        Minimum Setting Water Temperature: 0
        Maximum Setting Water Temperature: 0
        Heating Minimum Setting Water Temperature: 0
        Heating Maximum Setting Water Temperature: 0
        Use On Demand: UNKNOWN
        Heating Control: SUPPLY
        wwsdFlag: OK
        commercialLock: OK
        hotwaterPossibility: OFF
        recirculationPossibility: OFF
        High Temperature: TEMPERATURE_60
        Use Warm Water: OFF
Channel:3
        Device Model Type: NPE
        Device Count: 1
        Temp Flag: FAHRENHEIT
        Minimum Setting Water Temperature: 98
        Maximum Setting Water Temperature: 182
        Heating Minimum Setting Water Temperature: 32
        Heating Maximum Setting Water Temperature: 32
        Use On Demand: WARMUP
        Heating Control: SUPPLY
        wwsdFlag: OK
        commercialLock: OK
        hotwaterPossibility: OFF
        recirculationPossibility: OFF
        High Temperature: TEMPERATURE_60
        Use Warm Water: OFF
---------------------------


Channel 3 Info:
Device: 1
State
---------------------------
Controller Version: 1299
Panel Version: 28
Device Model Type: NPE
Device Count: 1
Current Channel: 3
Device Number: 1
Error Code: Normal
Operation Device Number: 0
Average Calorimeter: 0.0 %
Current Gas Usage: 0.0 BTU
Total Gas Usage: 59971.4 ft³
Hot Water Setting Temperature: 125 °F
Hot Water Current Temperature: 110 °F
Hot Water Flow Rate: 0.0 GPM
Inlet Temperature: 117 °F
Power Status: ON
Heat Status: OFF
Use On Demand: OFF
Weekly Control: OFF
Day Sequences
        SUN
                None
        MON
                None
        TUE
                None
        WED
                None
        THU
                None
        FRI
                None
        SAT
                None
---------------------------
```

**Comment by actionpotato** [comment]
Here is my output:

`--------------
Navien-API V1.0
--------------

---------------------------
Device ID: 8472072d354f1033
Nickname: HotWater
State: 1
Connected: 3/26/2022 11:00:31 PM
Server IP Address: 13.10.5.75
Server TCP Port Number: 6001
---------------------------

Channel Info
---------------------------
Channel:1
	Device Model Type: NO_DEVICE
	Device Count: 0
	Temp Flag: CELSIUS
	Minimum Setting Water Temperature: 0
	Maximum Setting Water Temperature: 0
	Heating Minimum Setting Water Temperature: 0
	Heating Maximum Setting Water Temperature: 0
	Use On Demand: UNKNOWN
	Heating Control: SUPPLY
	wwsdFlag: OK
	commercialLock: OK
	hotwaterPossibility: OFF
	recirculationPossibility: OFF
	High Temperature: TEMPERATURE_60
	Use Warm Water: OFF
Channel:2
	Device Model Type: NPE
	Device Count: 1
	Temp Flag: FAHRENHEIT
	Minimum Setting Water Temperature: 98
	Maximum Setting Water Temperature: 182
	Heating Minimum Setting Water Temperature: 32
	Heating Maximum Setting Water Temperature: 32
	Use On Demand: WARMUP
	Heating Control: SUPPLY
	wwsdFlag: OK
	commercialLock: OK
	hotwaterPossibility: OFF
	recirculationPossibility: OFF
	High Temperature: TEMPERATURE_60
	Use Warm Water: OFF
Channel:3
	Device Model Type: NO_DEVICE
	Device Count: 0
	Temp Flag: CELSIUS
	Minimum Setting Water Temperature: 0
	Maximum Setting Water Temperature: 0
	Heating Minimum Setting Water Temperature: 0
	Heating Maximum Setting Water Temperature: 0
	Use On Demand: UNKNOWN
	Heating Control: SUPPLY
	wwsdFlag: OK
	commercialLock: OK
	hotwaterPossibility: OFF
	recirculationPossibility: OFF
	High Temperature: TEMPERATURE_60
	Use Warm Water: OFF
---------------------------


Channel 2 Info:
Device: 1
State
---------------------------
Controller Version: 1300
Panel Version: 33
Device Model Type: NPE
Device Count: 1
Current Channel: 2
Device Number: 1
Error Code: Normal
Operation Device Number: 0
Average Calorimeter: 0.0 %
Current Gas Usage: 0.0 BTU
Total Gas Usage: 8510.8 ft³
Hot Water Setting Temperature: 125 °F
Hot Water Current Temperature: 95 °F
Hot Water Flow Rate: 0.0 GPM
Inlet Temperature: 116 °F
Power Status: ON
Heat Status: OFF
Use On Demand: OFF
Weekly Control: OFF
Day Sequences
	SUN
		None
	MON
		None
	TUE
		None
	WED
		None
	THU
		None
	FRI
		None
	SAT
		None
---------------------------


Done
`

**Comment by rudybrian** [comment]
@actionpotato thanks for that. Is your NPE device piped for recirculation? It looks like it currently configured for internal recirculation using the buffer tank (same configuration I am currently using). If your device is piped for external recirculation, it is possible that your installer didn't set the device up properly.

**Comment by rudybrian** [comment]
Closing as this has been adequately tested at this point.
