### ISSUE TITLE
No Longer Works...

### ISSUE THREAD

**Issue by megaz555** [rudybrian/PyNavienSmartControl#25]
Navien released an update and killed this API. The authentication system has changed from user ID to email address, and I believe there is now an authentication token.

Hope you can look into it and figure out the differences.

**Comment by benjamin1492** [comment]
Can confirm behavior noted by megaz555...integration no longer working.

**Comment by rudybrian** [comment]
It looks like there have been some major changes made with the release of the new mobile apps and there is now a v2 of the API being used. Will have a deeper look when I am able to break off some time.

**Comment by nikshriv** [comment]
I'm currently working on this to get my home assistant integration back up and running. I'm rewriting the backend now. I have managed to log in to the AWS IOT MQTT server and I'm able to receive status messages. Next step is to get water heater control working. Should have this working in the next week or so.

**Comment by rudybrian** [comment]
Hi folks, 

After some consideration, I think it's time to archive this project as it has served it's intended purpose. With Navien's new v2 protocol requiring a total refactor and @nikshriv having already fully integrated the changes into Home Assistant with his [actively maintained HASS integration](https://github.com/nikshriv/hass_navien_water_heater), it's time.

I am happy that my minor contribution along the way has led to what is now a usable IoT/Smart Home product.
